<?xml version="1.0" encoding="UTF-8"?>

<robot name="lw_mse6_bot" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find udacity_bot)/urdf/lw_mse6_bot.gazebo"/>
    <xacro:include filename="$(find udacity_bot)/urdf/macros.xacro" />
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="epsilon" value="0.0001"/>

    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.4"/>
    <xacro:property name="chassisWidth" value="0.2"/>
    <xacro:property name="chassisMass" value="15.0"/>

    <!-- <xacro:property name="casterRadius" value="0.05"/>
    <xacro:property name="casterMass" value="5"/> -->

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.1"/>
    <xacro:property name="wheelPos" value="0.2"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="cameraSize" value="0.05"/>
    <xacro:property name="cameraMass" value="0.1"/>

    <link name="robot_footprint"></link>

    <joint name="robot_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="robot_footprint"/>
        <child link="chassis" />
    </joint>

    <!-- <joint name="robot_footprint_body_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="robot_footprint"/>
        <child link="body" />
    </joint> -->

    <joint name="left_wheel_hinge" type="continuous">
        <origin xyz="0 ${wheelWidth + chassisWidth*0.5} 0" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="left_wheel"/>
        <axis xyz="0.0 1.0 0.0" rpy="0.0 0.0 0.0"/>
        <limit effort="10000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="right_wheel_hinge" type="continuous">
        <origin xyz="0 -${wheelWidth + chassisWidth*0.5} 0" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="right_wheel"/>
        <axis xyz="0.0 1.0 0.0" rpy="0.0 0.0 0.0"/>
        <limit effort="10000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0.3 0.0 0.08" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="camera"/>
    </joint>

    <joint name="hokuyo_joint" type="fixed">
        <origin xyz="0.2 0.0 0.15" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="hokuyo"/>
    </joint>

    <link name='chassis'>
        <pose>0 0 ${wheelRadius} 0 0 0</pose>
        <inertial>
            <mass value="18.0"/>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://udacity_bot/meshes/lw_mse6_chassis.dae"/>
            </geometry>
        </visual>
        <collision name='collision'>
            <!--  dims x: [-0.3 ... 0.375] y: [-0.15 ... 0.15] z: [ -0.056 ... 0.18 ] -->
            <!--<origin xyz="0.0375 0 0.062" rpy="0 0 0"/>
            <geometry>
                <box size="0.675 0.3 0.236"/>
            </geometry>-->
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://udacity_bot/meshes/lw_mse6_chassis.dae"/>
            </geometry>
        </collision>


        <!-- wheels -->
        <collision name='back_caster_collision'>
            <origin xyz="-0.15 0 -${wheelRadius/2}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheelRadius/2 - epsilon}"/>
            </geometry>
        </collision>

        <visual name='back_caster_visual'>
            <origin xyz="-0.15 0 -${wheelRadius/2}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheelRadius/2}"/>
            </geometry>
        </visual>

        <collision name='front_caster_collision'>
            <origin xyz="0.15 0 -${wheelRadius/2}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheelRadius/2 - epsilon}"/>
            </geometry>
        </collision>

        <visual name='front_caster_visual'>
            <origin xyz="0.15 0 -${wheelRadius/2}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheelRadius/2}"/>
            </geometry>
        </visual>
    </link>

    <!--<wheel lr="left"/>
    <wheel lr="right"/>-->

    <link name="left_wheel">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
            <mass value="5.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
        <visual name="left_wheel_visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0  1.5707 1.5707"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 0.7 1.0"/>
                <!-- <texture filename=""/> -->
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0  1.5707 1.5707"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
        </collision>
    </link>

    <link name="right_wheel">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 1.5707"/>
            <mass value="5.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
        <visual name="right_wheel_visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0  1.5707 1.5707"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 0.7 1.0"/>
                <!-- <texture filename=""/> -->
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0  1.5707 1.5707"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
        </collision>
    </link>

    <link name="camera">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.1"/>
            <inertia ixx="0.0000001" ixy="0.0" ixz="0.0" iyy="0.0000001" iyz="0.0" izz="0.0000001"/>
        </inertial>
        <visual name="camera_visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>
    </link>

    <link name="hokuyo">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.1"/>
            <inertia ixx="0.0000001" ixy="0.0" ixz="0.0" iyy="0.0000001" iyz="0.0" izz="0.0000001"/>
        </inertial>
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://udacity_bot/meshes/hokuyo.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
    </link>

</robot>